# Generated by Django 5.2.6 on 2025-09-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_regestration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='regestration',
            new_name='regestration',
        ),
    ]
