# Generated by Django 5.2.6 on 2025-09-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename__regestration_student_regestration'),
    ]

    operations = [
    ]
