# Generated by Django 5.2.6 on 2025-09-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_set_registration_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Student',
            new_name='student',
        ),
    ]
